### ISSUE TITLE
Issue creating a Gif or other format than png

### ISSUE THREAD

**Issue by FabiSmd** [AndreaDev3D/ThumbCreator#1]
Hey,

when I am trying to create a Gif file using the Thumb Creator, it generates one but I can not then find it in the desired folder, What shall I do to see my generated files? Using the png feature, it works all fine.

I dont know why it is doing this hm...

Maybe you can help me! Thanks

**Comment by AndreaDev3D** [comment]
As I removed GIF support this issue can be considered closed I guess.
